# Numpy Katas

Reference:
- https://github.com/rougier/numpy-100
- https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb
- https://medium.com/better-programming/numpy-illustrated-the-visual-guide-to-numpy-3b1d4976de1d
- https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises_with_hints_with_solutions.md

1. Import the numpy package under the name np (★☆☆):

In [1]:
import numpy as np

2. Print the numpy version and the configuration (★☆☆):

In [2]:
np.__version__

'1.20.1'

In [3]:
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


3. Create a null vector of size 10 (★☆☆):

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4. How to find the memory size of any array (★☆☆)

In [5]:
matrix = np.zeros((10, 10))

print('Size: %d bytes' % (matrix.size * matrix.itemsize))

Size: 800 bytes


5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
!python -c "import numpy; numpy.info(numpy.add)"

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆):

In [7]:
vector = np.zeros(10)
vector[4] = 1

vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

7. Create a vector with values ranging from 10 to 49 (★☆☆):

In [8]:
vector = np.arange(10, 50)

vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

8. Reverse a vector (first element becomes last) (★☆☆):

In [9]:
vector[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆):

In [10]:
matrix = np.arange(0, 9).reshape(3, 3)

matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10. Find indices of non-zero elements from (1,2,0,0,4,0) (★☆☆):

In [11]:
vector = [1, 2, 0, 0, 4, 0]

np.nonzero(vector)

(array([0, 1, 4]),)

11. Create a 3x3 identity matrix (★☆☆):

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

12. Create a 3x3x3 array with random values (★☆☆):

In [13]:
rng = np.random.default_rng()

rng.integers(0, 10, (3, 3, 3))

array([[[2, 5, 5],
        [7, 0, 0],
        [0, 5, 5]],

       [[3, 8, 4],
        [5, 8, 5],
        [6, 9, 2]],

       [[0, 9, 5],
        [4, 1, 5],
        [6, 8, 7]]])

13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆):

In [14]:
random_matrix = rng.standard_normal((10, 10))

print('Min: %f' % random_matrix.min())
print('Max: %f' % random_matrix.max())

Min: -2.232962
Max: 1.941247


14. Create a random vector of size 30 and find the mean value (★☆☆):

In [15]:
random_vector = rng.standard_normal(30)

random_vector.mean()

0.1371447947270164

15. Create a 2d array with 1 on the border and 0 inside (★☆☆):

In [16]:
zeros = np.ones((5, 5))

zeros[1:-1, 1:-1] = 0

zeros

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

16. How to add a border (filled with 0's) around an existing array? (★☆☆):

In [17]:
random_vector = rng.standard_normal((2, 2))

np.pad(random_vector, pad_width=1, mode='constant', constant_values=0)

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.17484505,  0.7926474 ,  0.        ],
       [ 0.        , -0.57687504, -0.37037393,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [18]:
random_vector = rng.standard_normal((3, 3))

random_vector[:, [0, -1]] = 0
random_vector[[0, -1], :] = 0

random_vector

array([[0.        , 0.        , 0.        ],
       [0.        , 0.77053611, 0.        ],
       [0.        , 0.        , 0.        ]])